sonar.projectKey=AparnaMounikau763_python-flask-app
sonar.organization=aparnamounikau763
sonar.sources=.

sonar.exclusions=tests/**

sonar.tests=tests

sonar.python.version=3.12

sonar.sourceEncoding=UTF-8