sonar.projectKey=AparnaMounikau763_python-flask-app
sonar.organization=aparnamounikau763

sonar.sources=.
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io