name: Python Application CI

on:
  push:
    branches:
      - main

jobs:

  pipeline:

    uses: AparnaMounikau763/github-actions-reusable-workflows/.github/workflows/python-reusable.yml@main

    with:
      python_version: "3.12"