name: Python Application CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  reusable-pipeline:
    uses: AparnaMounikau763/github-actions-reusable-workflows/.github/workflows/python-reusable.yml@main

    with:
      python_version: "3.12"
      image_name: "python-flask-app"

    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
